### ISSUE TITLE
AuthMe settings and autojoin

### ISSUE THREAD

**Issue by SeussCZ** [tanyaofei/minecraft-fakeplayer#13]
Very interesting plugin. Can you please advise me on how to set up AuthMe? I set "self-commands" but FakePlayer still won't login.

Also, is it possible to have FakePlayers automatically connect to a server using a list of names?

**Comment by tanyaofei** [comment]
1. Make sure `simulate-login` was set to `true`
2. Add tow commands in `self-commands`: 

```yaml
simulate-login: true
self-commands:
  - '/register anypassword'
  - '/login anypassword'
```
